version: ~> 1.0
language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
script:
   - 'if [ -n "${SES-}" ]; then npm run test:ses; fi'
matrix:
  include:
    - node_js: "14"
      env: SES=true
    - node_js: "12"
      env: SES=true
after_success:
 - 'if [ -f coverage/*.json ]; then bash <(curl -s https://codecov.io/bash) -f coverage/*.json; fi'
