name: 'Tests: SES'

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
           - 14
           - 12

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test:ses

  SES:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'